"""Tạo toàn bộ schema ban đầu — 21 bảng.

Sinh bằng `alembic revision --autogenerate` từ model trong app/db/all_models.py.
Đã bổ sung thủ công các index bộ phận (partial index) theo docs/design/04 §5.1.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-31 21:25:16.819220
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code'))
    )
    op.create_table('holidays',
    sa.Column('holiday_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('holiday_date', name=op.f('pk_holidays'))
    )
    op.create_table('kb_categories',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['kb_categories.id'], name=op.f('fk_kb_categories_parent_id_kb_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_kb_categories_slug'))
    )
    op.create_table('sla_policies',
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticket_priority'), nullable=False),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('business_hours_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('first_response_minutes > 0 AND resolution_minutes > 0', name=op.f('ck_sla_policies_positive')),
    sa.CheckConstraint('resolution_minutes >= first_response_minutes', name=op.f('ck_sla_policies_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_policies')),
    sa.UniqueConstraint('priority', name=op.f('uq_sla_policies_priority'))
    )
    op.create_table('ticket_categories',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticket_priority'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_ticket_categories_slug'))
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'IT_AGENT', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_agent_skills_agent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], name=op.f('fk_agent_skills_category_id_ticket_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'category_id', name=op.f('pk_agent_skills'))
    )
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('led_to_ticket', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.SmallInteger(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    op.create_table('kb_articles',
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='article_status'), nullable=False),
    sa.Column('kb_category_id', sa.UUID(), nullable=True),
    sa.Column('ticket_category_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'PUBLISHED' OR published_at IS NOT NULL", name=op.f('ck_kb_articles_published')),
    sa.CheckConstraint('char_length(content_md) >= 20', name=op.f('ck_kb_articles_content_len')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_kb_articles_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kb_category_id'], ['kb_categories.id'], name=op.f('fk_kb_articles_kb_category_id_kb_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_category_id'], ['ticket_categories.id'], name=op.f('fk_kb_articles_ticket_category_id_ticket_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_articles')),
    sa.UniqueConstraint('slug', name=op.f('uq_kb_articles_slug'))
    )
    op.create_index('ix_articles_search', 'kb_articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("type IN ('TICKET_ASSIGNED', 'TICKET_STATUS_CHANGED', 'TICKET_COMMENTED', 'TICKET_RESOLVED', 'SLA_AT_RISK', 'SLA_BREACHED', 'RATING_REQUESTED')", name=op.f('ck_notifications_type')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where='is_read = false')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_table('tickets',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_REQUESTER', 'RESOLVED', 'CLOSED', 'CANCELLED', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticket_priority'), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('WEB', 'CHATBOT', 'API', name='ticket_source'), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=True),
    sa.Column('ai_status', sa.Enum('PENDING', 'APPLIED', 'LOW_CONFIDENCE', 'SKIPPED', 'FAILED', name='ai_status'), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('sla_response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_resolution_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_seconds', sa.Integer(), nullable=False),
    sa.Column('sla_warned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('NEW', 'CANCELLED') OR assignee_id IS NOT NULL", name=op.f('ck_tickets_assignee')),
    sa.CheckConstraint("status NOT IN ('RESOLVED', 'CLOSED') OR (resolved_at IS NOT NULL AND char_length(coalesce(resolution_note, '')) >= 10)", name=op.f('ck_tickets_resolved')),
    sa.CheckConstraint('char_length(description) BETWEEN 10 AND 5000', name=op.f('ck_tickets_desc_len')),
    sa.CheckConstraint('char_length(title) BETWEEN 5 AND 200', name=op.f('ck_tickets_title_len')),
    sa.CheckConstraint('paused_seconds >= 0', name=op.f('ck_tickets_paused')),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tickets_assignee_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], name=op.f('fk_tickets_category_id_ticket_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_tickets_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_tickets_requester_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('code', name=op.f('uq_tickets_code'))
    )
    op.create_index('ix_tickets_assignee_status', 'tickets', ['assignee_id', 'status'], unique=False)
    op.create_index('ix_tickets_requester_created', 'tickets', ['requester_id', 'created_at'], unique=False)
    op.create_index('ix_tickets_search', 'tickets', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('ai_classifications',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('suggested_category_id', sa.UUID(), nullable=True),
    sa.Column('suggested_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticket_priority'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('was_applied', sa.Boolean(), nullable=False),
    sa.Column('was_accepted', sa.Boolean(), nullable=True),
    sa.Column('corrected_category_id', sa.UUID(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_category_id'], ['ticket_categories.id'], name=op.f('fk_ai_classifications_corrected_category_id_ticket_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['ticket_categories.id'], name=op.f('fk_ai_classifications_suggested_category_id_ticket_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ai_classifications_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_classifications'))
    )
    op.create_table('article_chunks',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['kb_articles.id'], name=op.f('fk_article_chunks_article_id_kb_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_chunks')),
    sa.UniqueConstraint('article_id', 'chunk_index', name='chunk')
    )
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('no_context_found', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_table('ticket_comments',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('char_length(body) BETWEEN 1 AND 5000', name=op.f('ck_ticket_comments_body_len')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ticket_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_comments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_comments'))
    )
    op.create_table('ticket_events',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'AI', name='actor_type'), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'ASSIGNED', 'UNASSIGNED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'RECLASSIFIED', 'COMMENTED', 'ATTACHMENT_ADDED', 'AI_CLASSIFIED', 'SLA_WARNED', 'SLA_BREACHED', 'RATED', 'REOPENED', 'AUTO_CLOSED', name='event_type'), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_ticket_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_events_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_events'))
    )
    op.create_table('ticket_ratings',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name=op.f('ck_ticket_ratings_score')),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_ticket_ratings_agent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name=op.f('fk_ticket_ratings_rater_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_ratings_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_ratings')),
    sa.UniqueConstraint('ticket_id', name=op.f('uq_ticket_ratings_ticket_id'))
    )
    op.create_table('chat_citations',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['kb_articles.id'], name=op.f('fk_chat_citations_article_id_kb_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['article_chunks.id'], name=op.f('fk_chat_citations_chunk_id_article_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_chat_citations_message_id_chat_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_citations'))
    )
    op.create_table('chat_feedback',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_chat_feedback_message_id_chat_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_feedback')),
    sa.UniqueConstraint('message_id', name=op.f('uq_chat_feedback_message_id'))
    )
    op.create_table('ticket_attachments',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('size_bytes > 0 AND size_bytes <= 10485760', name=op.f('ck_ticket_attachments_size')),
    sa.ForeignKeyConstraint(['comment_id'], ['ticket_comments.id'], name=op.f('fk_ticket_attachments_comment_id_ticket_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_attachments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_ticket_attachments_uploaded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_ticket_attachments_storage_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_attachments')
    op.drop_table('chat_feedback')
    op.drop_table('chat_citations')
    op.drop_table('ticket_ratings')
    op.drop_table('ticket_events')
    op.drop_table('ticket_comments')
    op.drop_table('chat_messages')
    op.drop_table('article_chunks')
    op.drop_table('ai_classifications')
    op.drop_index('ix_tickets_search', table_name='tickets', postgresql_using='gin')
    op.drop_index('ix_tickets_requester_created', table_name='tickets')
    op.drop_index('ix_tickets_assignee_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_notifications_unread', table_name='notifications', postgresql_where='is_read = false')
    op.drop_table('notifications')
    op.drop_index('ix_articles_search', table_name='kb_articles', postgresql_using='gin')
    op.drop_table('kb_articles')
    op.drop_table('idempotency_keys')
    op.drop_table('chat_sessions')
    op.drop_table('agent_skills')
    op.drop_table('users')
    op.drop_table('ticket_categories')
    op.drop_table('sla_policies')
    op.drop_table('kb_categories')
    op.drop_table('holidays')
    op.drop_table('departments')
    # ### end Alembic commands ###

    # ── BỔ SUNG THỦ CÔNG ──
    # Alembic autogenerate KHÔNG sinh lệnh xoá ENUM type. Thiếu phần này thì
    # `downgrade` rồi `upgrade` lại sẽ lỗi "type ... already exists" — và CI
    # có bước kiểm tra chính xác chu trình đó (docs/design/10 §9).
    for enum_name in (
        "user_role", "ticket_status", "ticket_priority", "ai_status",
        "actor_type", "event_type", "article_status", "message_role",
        "ticket_source",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
